<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><ApplicationManifest>app.manifest</ApplicationManifest></PropertyGroup><ItemGroup><PackageReference Include="Avalonia" /><PackageReference Include="Avalonia.Desktop" /><PackageReference Include="Avalonia.Themes.Fluent" /><ProjectReference Include="../Vexis.Foundation/Vexis.Foundation.csproj" /><ProjectReference Include="../Vexis.Commands/Vexis.Commands.csproj" /><ProjectReference Include="../Vexis.World/Vexis.World.csproj" /><ProjectReference Include="../Vexis.Modeling/Vexis.Modeling.csproj" /><ProjectReference Include="../Vexis.Runtime/Vexis.Runtime.csproj" /><ProjectReference Include="../Vexis.AI/Vexis.AI.csproj" /><ProjectReference Include="../Vexis.AI.Ollama/Vexis.AI.Ollama.csproj" /></ItemGroup></Project>